# copied from https://github.com/docker-library/openjdk/blob/445f8b8d18d7c61e2ae7fda76d8883b5d51ae0a5/8-jre/Dockerfile
FROM buildpack-deps:jessie-curl

EXPOSE 8000

COPY custom-jre/ /home/server

WORKDIR /home/server
CMD ["bin/java", "-m", "example.greeter.server/example.greeter.server.Runner"]
